name: CI Pipeline

on:
  push:
    branches: [ yileiyang/ci_cd ]
  pull_request:
    branches: [ yileiyang/ci_cd ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          activate-environment: github-ci-unit-test-env
          use-mamba: true
          channels: conda-forge, defaults
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y tox tox-conda py

      - name: Run unit tests
        shell: bash -l {0}
        run: tox
